<?php
// module/Brand/view/brand/brand/index.phtml:

$title = 'Brands';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('brand', ['action' => 'add']) ?>">Add new brand</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($brands as $brand) : ?>
    <tr>
        <td><?= $this->escapeHtml($brand->name) ?></td>
        <td>
            <a href="<?= $this->url('brand', ['action' => 'edit', 'id' => $brand->id]) ?>">Edit</a>
            <a href="<?= $this->url('brand', ['action' => 'delete', 'id' => $brand->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>