<?php
// module/Toy/view/toy/toy/index.phtml:

$title = 'Matteo\'s Toys';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('toy', ['action' => 'add']) ?>">Add new toy</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Brand</th>
    <th>Playing since</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($toys as $toy) : ?>
    <tr>
        <td><?= $this->escapeHtml($toy->name) ?></td>
        <td><?= $this->escapeHtml($toy->id_brand) ?></td>
        <td><?= $this->escapeHtml($toy->date_add) ?></td>
        <td>
            <a href="<?= $this->url('toy', ['action' => 'edit', 'id' => $toy->id]) ?>">Edit</a>
            <a href="<?= $this->url('toy', ['action' => 'delete', 'id' => $toy->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>